E_Ticket/Controllers/ActorController.cs
using AutoMapper;
using E_ticket.BLL.Interfaces;
using E_ticket.DLL.Models;
using E_Ticket.BLL.Interfaces;
using E_Ticket.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace E_Ticket.Controllers
{
    public class ActorController : Controller
    {
      //  private readonly IGenericRepository<Actor> genericRepo;
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public ActorController(IUnitOfWork unitOfWork,IMapper mapper)
        {
           // this.genericRepo = genericRepo;
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var  actors= await unitOfWork.ActorgenericRepository.GetAllAsync();

            var MappedActors =  mapper.Map<IEnumerable<Actor>,IEnumerable<ActorViewModel>>(actors);
            return View(MappedActors);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ActorViewModel model)
        {
            if(ModelState.IsValid)
            {
                var mappedactor=mapper.Map<ActorViewModel,Actor>(model);
               await unitOfWork.ActorgenericRepository.AddAsync(mappedactor);
             await unitOfWork.Complete(); 
        
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id,string name="Details")
        {
            if (id == null)
                return BadRequest();
            var actor =await unitOfWork.ActorgenericRepository.GetById(id.Value);
            if (actor == null)
                return NotFound();

            var mappedactor =  mapper.Map<Actor, ActorViewModel>(actor);
            return View(name,mappedactor);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]

        public async Task<IActionResult> Edit(ActorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedactor = mapper.Map<ActorViewModel, Actor>(model);
                 unitOfWork.ActorgenericRepository.Update(mappedactor);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]

        public async Task<IActionResult>Delete(ActorViewModel model)
        {
            
           if(model is not null)
            {
                var mappedactor=mapper.Map<ActorViewModel,Actor>(model);
                unitOfWork.ActorgenericRepository.Delete(mappedactor);
               await unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }

    }
}

E_Ticket/Controllers/CinemaController.cs
using AutoMapper;
using E_ticket.BLL.Interfaces;
using E_ticket.DLL.Models;
using E_Ticket.BLL.Interfaces;
using E_Ticket.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace E_Ticket.Controllers
{
    public class CinemaController : Controller
    {
      //  private readonly IGenericRepository<Cinema> genericRepo;
        private readonly IMapper mapper;
        private readonly IUnitOfWork unitOfWork;

        public CinemaController(IGenericRepository<Cinema> genericRepo,IMapper mapper,IUnitOfWork unitOfWork)
        {
         //   this.genericRepo = genericRepo;
            this.mapper = mapper;
            this.unitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index()
        {
            var cinemas = await unitOfWork.CinemagenericRepository.GetAllAsync();
            var MappedCineam = mapper.Map<IEnumerable<Cinema>,IEnumerable<CinemaViewModel>>(cinemas);
            return View(MappedCineam);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CinemaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedCinema = mapper.Map<CinemaViewModel, Cinema>(model);
                await unitOfWork.CinemagenericRepository.AddAsync(mappedCinema);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, string name = "Details")
        {
            if (id == null)
                return BadRequest();
            var Cinema = await unitOfWork.CinemagenericRepository.GetById(id.Value);
            if (Cinema == null)
                return NotFound();

            var mappedCinema = mapper.Map<Cinema, CinemaViewModel>(Cinema);
            return View(name, mappedCinema);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]

        public async Task<IActionResult> Edit(CinemaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedCinema = mapper.Map<CinemaViewModel, Cinema>(model);
                unitOfWork.CinemagenericRepository.Update(mappedCinema);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]

        public async Task<IActionResult> Delete(CinemaViewModel model)
        {

            if (model is not null)
            {
                var mappedCinema = mapper.Map<CinemaViewModel, Cinema>(model);
                unitOfWork.CinemagenericRepository.Delete(mappedCinema);
                await unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }



    }
}

E_Ticket/Controllers/MovieController.cs
using AutoMapper;
using E_ticket.BLL.Interfaces;
using E_ticket.DLL.Models;
using E_Ticket.BLL.Interfaces;
using E_Ticket.BLL.Specification;
using E_Ticket.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace E_Ticket.Controllers
{
    public class MovieController : Controller
    {
     //   private readonly IGenericRepository<Movie> genericRepo;
        private readonly IMapper mapper;
        private readonly IUnitOfWork unitOfWork;

        public MovieController(IGenericRepository<Movie> genericRepo,IMapper mapper,IUnitOfWork unitOfWork)
        {
          //  this.genericRepo = genericRepo;
            this.mapper = mapper;
            this.unitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index()
        {
            MovieSpecification spec=new MovieSpecification();
            var movies = await unitOfWork.MoviegenericRepository.GetAllAsyncBySpecification(spec);
          var  MappedMovies = mapper.Map<IEnumerable<Movie>,IEnumerable<MovieViewModel>>(movies);


            return View(MappedMovies);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MovieViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedMovie = mapper.Map<MovieViewModel, Movie>(model);
                await unitOfWork.MoviegenericRepository.AddAsync(mappedMovie);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, string name = "Details")
        {
            if (id == null)
                return BadRequest();
            var movie = await unitOfWork.MoviegenericRepository.GetById(id.Value);
            if (movie == null)
                return NotFound();

            var mappedMovie = mapper.Map<Movie, MovieViewModel>(movie);
            return View(name, mappedMovie);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]

        public async Task<IActionResult> Edit(MovieViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedMovie = mapper.Map<MovieViewModel, Movie>(model);
                unitOfWork.MoviegenericRepository.Update(mappedMovie);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]

        public async Task<IActionResult> Delete(MovieViewModel model)
        {

            if (model is not null)
            {
                var mappedMovie = mapper.Map<MovieViewModel, Movie>(model);
                unitOfWork.MoviegenericRepository.Delete(mappedMovie);
                await unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }



    }
}

E_Ticket/Controllers/ProducerController.cs
using AutoMapper;
using E_ticket.BLL.Interfaces;
using E_ticket.DLL.Models;
using E_Ticket.BLL.Interfaces;
using E_Ticket.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace E_Ticket.Controllers
{
    public class ProducerController : Controller
    {
       // private readonly IGenericRepository<Producer> genericRepo;
        private readonly IMapper mapper;
        private readonly IUnitOfWork unitOfWork;

        public ProducerController(IGenericRepository<Producer> genericRepo,IMapper mapper,IUnitOfWork unitOfWork)
        {

           // this.genericRepo = genericRepo;
            this.mapper = mapper;
            this.unitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index()
        {
            var producers = await unitOfWork.ProducergenericRepository.GetAllAsync();
            var MappedProducers = mapper.Map<IEnumerable<Producer>, IEnumerable<ProducerViewModel>>(producers);
            return View(MappedProducers);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProducerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedProducer = mapper.Map<ProducerViewModel, Producer>(model);
                await unitOfWork.ProducergenericRepository.AddAsync(mappedProducer);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, string name = "Details")
        {
            if (id == null)
                return BadRequest();
            var producer = await unitOfWork.ProducergenericRepository.GetById(id.Value);
            if (producer == null)
                return NotFound();

            var mappedProducer = mapper.Map<Producer, ProducerViewModel>(producer);
            return View(name, mappedProducer);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]

        public async Task<IActionResult> Edit(ProducerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedProducer = mapper.Map<ProducerViewModel, Producer>(model);
                unitOfWork.ProducergenericRepository.Update(mappedProducer);
                await unitOfWork.Complete();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult>Delete(int id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]

        public async Task<IActionResult> Delete(ProducerViewModel model)
        {

            if (model is not null)
            {
                var mappedProducer = mapper.Map<ProducerViewModel, Producer>(model);
                unitOfWork.ProducergenericRepository.Delete(mappedProducer);
                await unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }


    }
}

E_Ticket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <!-- Include Bootstrap CSS (replace 'version' with your desired version) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@1.4.1/dist/css/bootstrap.min.css">
    <!-- Include Bootstrap JS (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@1.4.1/dist/js/bootstrap.min.js"></script>
    <!-- Include Bootstrap Icons CSS (replace 'version' with your desired version) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movie" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>

                        
                        
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        

                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Movie" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                   

                  
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
   @await RenderSectionAsync("script", required: false)
   
</body>
</html>